export enum Type {
    int = 'int type',
    double = 'double type',
    boolean = 'boolean type',
    char = 'char type',
    String = 'String type',
    void = 'void type',

    break = 'break',
    case = 'case',
    continue = 'continue',
    default = 'default',
    do = 'do',
    else = 'else',
    for = 'for',
    if = 'if',
    import = 'import',
    print = 'print',
    println = 'println',
    return = 'return',
    switch = 'switch',
    while = 'while',
    invokeMethod = 'invoke method',

    sum = 'sum',
    subtraction = 'subtraction',
    multiplication = 'multiplication',
    division = 'division',
    power = 'power',
    module = 'module',
    greaterT = "Greater than",
    greaterTOET = "Greater than or equal to",
    lessT = "Less than",
    lessTOET = "Less than or equal to",
    equality = "Equality",
    inequality = "Inequality",
    or = "Logical OR",
    and = "Logical AND",
    not = "Logical NOT",
    negation = "Negation",
    decrement = "Decrement",
    increment = "Increment",

    null = "NULL"
};
